---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Import Data

```{r , message=FALSE, warning=FALSE}
data <- read_csv(file = "week4_australian_salary.csv") %>% 
  mutate(occupation = str_replace(occupation, pattern = "\x96", replacement = "-")) %>% 
  mutate(occupation = str_replace(occupation, pattern = "\x92", replacement = "")) %>% 
  arrange(gender, desc(average_taxable_income)) %>% 
  select(c(occupation, gender, average_taxable_income))
```

# Tidy up

Here is my approach to getting the first 50

```{r}
top_jobs <- data %>% 
  group_by(gender) %>% 
  top_n(50)
```
So here is the table for females
```{r}
top_jobs %>% 
  filter(gender == "Female") %>% 
  select(-gender) %>% 
  knitr::kable()
```
And males
```{r}
top_jobs %>% 
  filter(gender == "Male") %>% 
  select(-gender) %>% 
  knitr::kable()
```


# Graphing

```{r}
data %>%   
  mutate(income = average_taxable_income/100000) %>%
  group_by(gender) %>% 
  top_n(10) %>% 
  mutate(rank = rank(income)) %>% 
  mutate(income = ifelse(test = gender == "Female", yes = -income, no = income)) %>% 
  ggplot(aes(x = rank, y = income,
             fill = gender,
             ymin = -6,
             ymax = 8.5
  )) +
  geom_col() +
  geom_text(aes(x = rank,y = 0.5*income,
  label = occupation
  ), size = 1.8) +
  geom_label(aes(
    x = rank,
    y = ifelse(test = gender == "Female", 1.5 * income, 1.3 * income),
    label = paste("$", format(100000 * abs(income), big.mark = ","))
  ), fill = "white") +
  xlab("Gender") +
  ylab("Average Taxable Income (Hundreds of Thousands of Dollars)") +
  labs(title = "Top 10 Highest-Paid Occupations", fill = "Gender") +
  scale_y_continuous(labels = abs) +
  theme_bw() +
  coord_flip() +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(), 
        axis.ticks.y = element_blank()) 

ggsave(filename = "plot1.png", device = "png", plot = last_plot())

```


